export interface EvoNode {
  id: string;
  label: string;
  sublabel?: string;
  cluster: "HUB" | "USERS" | "MODS" | "ADMIN" | "BOTS";
  role?: string;
  x: number;
  y: number;
  radius: number;
  color: string;
  glowColor: string;
  icon?: "user" | "shield" | "lock" | "bell" | "bot" | "sliders" | "chart" | "hub";
  status?: "ACTIVE" | "AWAY" | "ALERT" | "STANDBY";
  latencyMs?: number;
  metrics?: {
    accuracy?: number;
    learningProgress?: number;
    responseTimeMs?: number;
    activityLogMs?: number;
    sparkline?: number[];
  };
  details?: {
    joinDate?: string;
    protocol?: string;
    tools?: string[];
  };
}

export interface EvoLink {
  id: string;
  sourceId: string;
  targetId: string;
  color: string;
  latencyLabel?: string;
  curvature?: number; // bezier bend factor
  pulseSpeed?: number; // speed of travelling packet
}

export const EVO_CLUSTERS = {
  HUB: {
    title: "MAIN HUB",
    subtitle: "LIVE ACTIVITY",
    color: "#06B6D4",
    accent: "#EC4899",
    glow: "rgba(6, 182, 212, 0.4)",
  },
  USERS: {
    title: "USER POPULATION",
    subtitle: "Active Community Net",
    color: "#38BDF8",
    accent: "#0284C7",
    glow: "rgba(56, 189, 248, 0.4)",
  },
  MODS: {
    title: "MODERATOR TEAM",
    subtitle: "Range Marshal Watch",
    color: "#F43F5E",
    accent: "#E11D48",
    glow: "rgba(244, 63, 94, 0.4)",
  },
  ADMIN: {
    title: "ADMIN CONTROLS",
    subtitle: "Security & Global Protocols",
    color: "#06B6D4",
    accent: "#6366F1",
    glow: "rgba(99, 102, 241, 0.4)",
  },
  BOTS: {
    title: "AI BOTS TEST BED",
    subtitle: "Autonomous Simulation Fleet",
    color: "#F59E0B",
    accent: "#D97706",
    glow: "rgba(245, 158, 11, 0.4)",
  },
};

export const EVO_NODES: EvoNode[] = [
  // ─── 1. CENTRAL MAIN HUB ──────────────────────────────────────────
  {
    id: "hub-main",
    label: "MAIN HUB",
    sublabel: "LIVE ACTIVITY",
    cluster: "HUB",
    x: 0,
    y: 0,
    radius: 68,
    color: "#06B6D4",
    glowColor: "rgba(6, 182, 212, 0.5)",
    icon: "hub",
    status: "ACTIVE",
    latencyMs: 1,
    metrics: {
      responseTimeMs: 1,
      sparkline: [22, 35, 45, 60, 48, 70, 85, 65, 90, 78],
    },
  },

  // ─── 2. USER POPULATION CLUSTER (Top-Left) ────────────────────────
  {
    id: "cluster-users",
    label: "USER POPULATION",
    sublabel: "Active Members",
    cluster: "USERS",
    x: -360,
    y: -160,
    radius: 46,
    color: "#38BDF8",
    glowColor: "rgba(56, 189, 248, 0.5)",
    icon: "user",
    status: "ACTIVE",
    latencyMs: 4,
  },
  {
    id: "user-comm-groups",
    label: "COMMUN GROUPS",
    sublabel: "Squad Comms",
    cluster: "USERS",
    x: -210,
    y: -100,
    radius: 34,
    color: "#22D3EE",
    glowColor: "rgba(34, 211, 238, 0.4)",
    icon: "user",
    status: "ACTIVE",
    latencyMs: 16,
  },
  {
    id: "user-1",
    label: "Wyatt_S",
    sublabel: "Join: Oct 13, 2026",
    cluster: "USERS",
    x: -480,
    y: -260,
    radius: 17,
    color: "#38BDF8",
    glowColor: "rgba(56, 189, 248, 0.3)",
    icon: "user",
    status: "ACTIVE",
    latencyMs: 3,
  },
  {
    id: "user-2",
    label: "Kendra_C",
    sublabel: "Join: Oct 11, 2026",
    cluster: "USERS",
    x: -420,
    y: -300,
    radius: 17,
    color: "#38BDF8",
    glowColor: "rgba(56, 189, 248, 0.3)",
    icon: "user",
    status: "ACTIVE",
    latencyMs: 5,
  },
  {
    id: "user-3",
    label: "ApexShooter",
    sublabel: "Join: Oct 14, 2026",
    cluster: "USERS",
    x: -330,
    y: -300,
    radius: 17,
    color: "#38BDF8",
    glowColor: "rgba(56, 189, 248, 0.3)",
    icon: "user",
    status: "ACTIVE",
    latencyMs: 2,
  },
  {
    id: "user-4",
    label: "Vance_MD",
    sublabel: "Join: Sep 28, 2026",
    cluster: "USERS",
    x: -520,
    y: -190,
    radius: 17,
    color: "#38BDF8",
    glowColor: "rgba(56, 189, 248, 0.3)",
    icon: "user",
    status: "ACTIVE",
    latencyMs: 8,
  },
  {
    id: "user-5",
    label: "RimfirePro",
    sublabel: "Join: Oct 15, 2026",
    cluster: "USERS",
    x: -510,
    y: -110,
    radius: 17,
    color: "#38BDF8",
    glowColor: "rgba(56, 189, 248, 0.3)",
    icon: "user",
    status: "ACTIVE",
    latencyMs: 10,
  },
  {
    id: "user-6",
    label: "ColdBore99",
    sublabel: "Join: Oct 16, 2026",
    cluster: "USERS",
    x: -460,
    y: -40,
    radius: 17,
    color: "#E879F9",
    glowColor: "rgba(232, 121, 249, 0.3)",
    icon: "user",
    status: "AWAY",
    latencyMs: 14,
  },
  {
    id: "user-7",
    label: "Hunter_East",
    sublabel: "Join: Oct 17, 2026",
    cluster: "USERS",
    x: -380,
    y: -30,
    radius: 17,
    color: "#FBBF24",
    glowColor: "rgba(251, 191, 36, 0.3)",
    icon: "user",
    status: "STANDBY",
    latencyMs: 9,
  },
  {
    id: "user-8",
    label: "SubZero_457",
    sublabel: "Join: Oct 12, 2026",
    cluster: "USERS",
    x: -300,
    y: -50,
    radius: 17,
    color: "#38BDF8",
    glowColor: "rgba(56, 189, 248, 0.3)",
    icon: "user",
    status: "ACTIVE",
    latencyMs: 11,
  },

  // ─── 3. MODERATOR TEAM CLUSTER (Top-Right) ────────────────────────
  {
    id: "cluster-mods",
    label: "MODERATOR TEAM",
    sublabel: "Range Marshals",
    cluster: "MODS",
    x: 360,
    y: -160,
    radius: 46,
    color: "#F43F5E",
    glowColor: "rgba(244, 63, 94, 0.5)",
    icon: "shield",
    status: "ACTIVE",
    latencyMs: 6,
  },
  {
    id: "mod-room-1",
    label: "HOST ROOM 1",
    sublabel: "Chat Room 1",
    cluster: "MODS",
    x: 500,
    y: -260,
    radius: 26,
    color: "#FB7185",
    glowColor: "rgba(251, 113, 133, 0.4)",
    icon: "chart",
    status: "ACTIVE",
    latencyMs: 8,
    metrics: {
      responseTimeMs: 8,
      activityLogMs: 20,
      sparkline: [10, 24, 18, 45, 32, 58, 42, 65, 30],
    },
  },
  {
    id: "mod-room-12",
    label: "HOST ROOM 12",
    sublabel: "Chat Room 2",
    cluster: "MODS",
    x: 540,
    y: -160,
    radius: 26,
    color: "#FB7185",
    glowColor: "rgba(251, 113, 133, 0.4)",
    icon: "chart",
    status: "ACTIVE",
    latencyMs: 18,
    metrics: {
      responseTimeMs: 18,
      activityLogMs: 32,
      sparkline: [20, 15, 30, 25, 48, 38, 70, 52, 60],
    },
  },
  {
    id: "mod-room-23",
    label: "HOST ROOM 23",
    sublabel: "Chat Room 3",
    cluster: "MODS",
    x: 500,
    y: -60,
    radius: 26,
    color: "#FB7185",
    glowColor: "rgba(251, 113, 133, 0.4)",
    icon: "chart",
    status: "ACTIVE",
    latencyMs: 12,
    metrics: {
      responseTimeMs: 12,
      activityLogMs: 6,
      sparkline: [8, 12, 15, 22, 18, 30, 24, 38, 20],
    },
  },
  {
    id: "mod-plink",
    label: "PLINK SENTINEL",
    sublabel: "AI Range Marshal",
    cluster: "MODS",
    x: 640,
    y: -220,
    radius: 20,
    color: "#F43F5E",
    glowColor: "rgba(244, 63, 94, 0.4)",
    icon: "shield",
    status: "ACTIVE",
    latencyMs: 4,
  },

  // ─── 4. ADMIN CONTROLS CLUSTER (Bottom-Left) ──────────────────────
  {
    id: "cluster-admin",
    label: "ADMIN CONTROLS",
    sublabel: "System Security",
    cluster: "ADMIN",
    x: -360,
    y: 190,
    radius: 46,
    color: "#06B6D4",
    glowColor: "rgba(6, 182, 212, 0.5)",
    icon: "lock",
    status: "ACTIVE",
    latencyMs: 5,
  },
  {
    id: "admin-alerts",
    label: "SYSTEM ALERTS",
    sublabel: "Comms Abuse Queue",
    cluster: "ADMIN",
    x: -540,
    y: 110,
    radius: 24,
    color: "#F43F5E",
    glowColor: "rgba(244, 63, 94, 0.4)",
    icon: "bell",
    status: "ALERT",
    latencyMs: 33,
  },
  {
    id: "admin-audits",
    label: "SYSTEM AUDITS",
    sublabel: "Event Telemetry",
    cluster: "ADMIN",
    x: -560,
    y: 180,
    radius: 20,
    color: "#A855F7",
    glowColor: "rgba(168, 85, 247, 0.4)",
    icon: "lock",
    status: "ACTIVE",
    latencyMs: 112,
  },
  {
    id: "admin-security",
    label: "SECURITY PROTOCOLS",
    sublabel: "NFA & Conduct Filters",
    cluster: "ADMIN",
    x: -540,
    y: 260,
    radius: 24,
    color: "#8B5CF6",
    glowColor: "rgba(139, 92, 246, 0.4)",
    icon: "lock",
    status: "ACTIVE",
    latencyMs: 240,
  },
  {
    id: "admin-users",
    label: "USER MANAGEMENT",
    sublabel: "Member Credentials",
    cluster: "ADMIN",
    x: -470,
    y: 330,
    radius: 24,
    color: "#06B6D4",
    glowColor: "rgba(6, 182, 212, 0.4)",
    icon: "sliders",
    status: "ACTIVE",
    latencyMs: 28,
  },

  // ─── 5. AI BOTS TEST BED CLUSTER (Bottom-Right) ───────────────────
  {
    id: "cluster-bots",
    label: "AI BOTS TEST BED",
    sublabel: "Fleet Simulation",
    cluster: "BOTS",
    x: 360,
    y: 190,
    radius: 48,
    color: "#F59E0B",
    glowColor: "rgba(245, 158, 11, 0.5)",
    icon: "bot",
    status: "ACTIVE",
    latencyMs: 10,
    metrics: {
      learningProgress: 88,
      accuracy: 94,
    },
  },
  {
    id: "bot-scenario",
    label: "TEST SCENARIO",
    sublabel: "Learning: 80%",
    cluster: "BOTS",
    x: 480,
    y: 90,
    radius: 22,
    color: "#FBBF24",
    glowColor: "rgba(251, 191, 36, 0.4)",
    icon: "bot",
    status: "ACTIVE",
    metrics: {
      learningProgress: 80,
      accuracy: 85,
    },
  },
  {
    id: "bot-1-inst",
    label: "GHOST [MD-01]",
    sublabel: "Accuracy: 96%",
    cluster: "BOTS",
    x: 580,
    y: 110,
    radius: 20,
    color: "#F59E0B",
    glowColor: "rgba(245, 158, 11, 0.4)",
    icon: "bot",
    status: "ACTIVE",
    metrics: {
      accuracy: 96,
      responseTimeMs: 32,
    },
  },
  {
    id: "bot-2-inst",
    label: "COLDBORE [PRO]",
    sublabel: "Accuracy: 88%",
    cluster: "BOTS",
    x: 620,
    y: 180,
    radius: 20,
    color: "#F59E0B",
    glowColor: "rgba(245, 158, 11, 0.4)",
    icon: "bot",
    status: "ACTIVE",
    metrics: {
      accuracy: 88,
      responseTimeMs: 60,
    },
  },
  {
    id: "bot-marcus-badactor",
    label: "IRONHIDE [TESTER]",
    sublabel: "Bad Actor Stress: 15%",
    cluster: "BOTS",
    x: 610,
    y: 260,
    radius: 22,
    color: "#EF4444",
    glowColor: "rgba(239, 68, 68, 0.5)",
    icon: "bot",
    status: "ALERT",
    metrics: {
      accuracy: 72,
      responseTimeMs: 18,
      sparkline: [12, 18, 45, 90, 30, 85, 20],
    },
  },
  {
    id: "bot-vip",
    label: "VIPER [PROD]",
    sublabel: "Accuracy: 91%",
    cluster: "BOTS",
    x: 550,
    y: 330,
    radius: 20,
    color: "#F59E0B",
    glowColor: "rgba(245, 158, 11, 0.4)",
    icon: "bot",
    status: "ACTIVE",
    metrics: {
      accuracy: 91,
      responseTimeMs: 24,
    },
  },
  {
    id: "bot-dialed",
    label: "DIALED [NEWBIE]",
    sublabel: "Reaction Rate: 70%",
    cluster: "BOTS",
    x: 460,
    y: 340,
    radius: 18,
    color: "#FBBF24",
    glowColor: "rgba(251, 191, 36, 0.3)",
    icon: "bot",
    status: "ACTIVE",
  },
];

export const EVO_LINKS: EvoLink[] = [
  // Trunks from Central Hub
  { id: "link-hub-users", sourceId: "hub-main", targetId: "cluster-users", color: "#06B6D4", latencyLabel: "4 ms", curvature: 0.15, pulseSpeed: 0.8 },
  { id: "link-hub-comm", sourceId: "hub-main", targetId: "user-comm-groups", color: "#22D3EE", latencyLabel: "16 ms", curvature: -0.1, pulseSpeed: 1.1 },
  { id: "link-hub-mods", sourceId: "hub-main", targetId: "cluster-mods", color: "#F43F5E", latencyLabel: "6 ms", curvature: -0.15, pulseSpeed: 0.9 },
  { id: "link-hub-admin", sourceId: "hub-main", targetId: "cluster-admin", color: "#06B6D4", latencyLabel: "5 ms", curvature: -0.12, pulseSpeed: 0.7 },
  { id: "link-hub-bots", sourceId: "hub-main", targetId: "cluster-bots", color: "#F59E0B", latencyLabel: "10 ms", curvature: 0.12, pulseSpeed: 1.0 },

  // User cluster branches
  { id: "link-users-comm", sourceId: "cluster-users", targetId: "user-comm-groups", color: "#38BDF8", latencyLabel: "16" },
  { id: "link-users-u1", sourceId: "cluster-users", targetId: "user-1", color: "#38BDF8", latencyLabel: "3" },
  { id: "link-users-u2", sourceId: "cluster-users", targetId: "user-2", color: "#38BDF8", latencyLabel: "5" },
  { id: "link-users-u3", sourceId: "cluster-users", targetId: "user-3", color: "#38BDF8", latencyLabel: "2" },
  { id: "link-users-u4", sourceId: "cluster-users", targetId: "user-4", color: "#38BDF8", latencyLabel: "8" },
  { id: "link-users-u5", sourceId: "cluster-users", targetId: "user-5", color: "#38BDF8", latencyLabel: "10" },
  { id: "link-users-u6", sourceId: "cluster-users", targetId: "user-6", color: "#E879F9", latencyLabel: "14" },
  { id: "link-users-u7", sourceId: "cluster-users", targetId: "user-7", color: "#FBBF24", latencyLabel: "9" },
  { id: "link-users-u8", sourceId: "cluster-users", targetId: "user-8", color: "#38BDF8", latencyLabel: "11" },

  // Moderator cluster branches
  { id: "link-mods-r1", sourceId: "cluster-mods", targetId: "mod-room-1", color: "#F43F5E", latencyLabel: "55 ms", curvature: 0.1 },
  { id: "link-mods-r2", sourceId: "cluster-mods", targetId: "mod-room-12", color: "#F43F5E", latencyLabel: "160 ms" },
  { id: "link-mods-r3", sourceId: "cluster-mods", targetId: "mod-room-23", color: "#F43F5E", latencyLabel: "110 ms", curvature: -0.1 },
  { id: "link-r1-plink", sourceId: "mod-room-1", targetId: "mod-plink", color: "#FB7185", latencyLabel: "8 ms" },

  // Admin cluster branches
  { id: "link-admin-alerts", sourceId: "cluster-admin", targetId: "admin-alerts", color: "#F43F5E", latencyLabel: "33 ms" },
  { id: "link-admin-audits", sourceId: "cluster-admin", targetId: "admin-audits", color: "#A855F7", latencyLabel: "112 ms" },
  { id: "link-admin-sec", sourceId: "cluster-admin", targetId: "admin-security", color: "#8B5CF6", latencyLabel: "240 ms" },
  { id: "link-admin-users", sourceId: "cluster-admin", targetId: "admin-users", color: "#06B6D4", latencyLabel: "28 ms" },

  // AI Bots cluster branches
  { id: "link-bots-scenario", sourceId: "cluster-bots", targetId: "bot-scenario", color: "#F59E0B", latencyLabel: "12 ms" },
  { id: "link-bots-b1", sourceId: "cluster-bots", targetId: "bot-1-inst", color: "#F59E0B", latencyLabel: "25 ms" },
  { id: "link-bots-b2", sourceId: "cluster-bots", targetId: "bot-2-inst", color: "#F59E0B", latencyLabel: "110 ms" },
  { id: "link-bots-badactor", sourceId: "cluster-bots", targetId: "bot-marcus-badactor", color: "#EF4444", latencyLabel: "18 ms", pulseSpeed: 1.4 },
  { id: "link-bots-vip", sourceId: "cluster-bots", targetId: "bot-vip", color: "#F59E0B", latencyLabel: "55 ms" },
  { id: "link-bots-dialed", sourceId: "cluster-bots", targetId: "bot-dialed", color: "#FBBF24", latencyLabel: "70 ms" },
];
