import { MatchEvent, FacebookPostItem, AthleteProfile, ChatMessage } from "./types";

export const INITIAL_MATCHES: MatchEvent[] = [
  {
    id: "bristol-pro-invitational-2026",
    title: "Appalachian Mountain Rimfire Pro Invitational",
    subtitle: "The Premier Precision Rimfire Shootout in the Bristol TN High Country",
    date: "October 17-18, 2026",
    time: "07:00 AM EST Check-in",
    location: "Bristol Mountain Precision Facility, Bristol, TN",
    locationDetails: "Ridge Line Sector 4, Holston Mountain Valley, Bristol, TN 37620",
    coordinates: {
      lat: 36.5951,
      lng: -82.1887,
    },
    tier: "PRO_SERIES",
    stages: 18,
    roundCount: 220,
    distanceRange: "35 – 465 Yards",
    maxCompetitors: 120,
    registeredCount: 94,
    entryFee: 275,
    prizePool: "$28,500 Cash & Gear Table",
    matchDirector: {
      name: "Garrett 'Vapor' Vance",
      callsign: "MD-01",
      email: "director@subsonicsociety.com",
      phone: "(423) 555-0198",
    },
    description:
      "Perched high on the ridgeline overlooking the East Tennessee mountains, the Appalachian Mountain Pro Invitational tests competitors against drastic elevation changes, variable thermal mountain drafts, and steel targets stretched out to a staggering 465 yards. Pro shooters and top regional marksmen will battle across two grueling days for the coveted Subsonic Society Championship Cup and challenge coin.",
    stageBriefs: [
      {
        stageNumber: 1,
        name: "Holston Gap High-Angle Sniper",
        distance: "185 yds – 340 yds",
        targetType: "66% IPSC & Diamond Steel",
        roundCount: 12,
        timeLimit: "90 seconds",
        description: "Engage targets from a steep 22-degree downhill natural boulder prop. Crosswind through the mountain notch requires aggressive wind holds.",
      },
      {
        stageNumber: 2,
        name: "The Bristol KYL Gauntlet",
        distance: "85 yds & 150 yds",
        targetType: "Know-Your-Limits 5-Paddles (2.0\" down to 0.25\")",
        roundCount: 10,
        timeLimit: "75 seconds",
        description: "Clean the near rack clean before moving to the 150-yard secondary rack. Any miss wipes all stage points earned so far.",
      },
      {
        stageNumber: 3,
        name: "Mountain Rooftop Positional",
        distance: "115 yds – 260 yds",
        targetType: "Round Gongs (4\" to 8\")",
        roundCount: 12,
        timeLimit: "90 seconds",
        description: "Fire two shots per target from three positions along a steep metal rooftop prop with slick footing.",
      },
      {
        stageNumber: 4,
        name: "Subsonic 400-Yard Terminal Glide",
        distance: "425 yds – 465 yds",
        targetType: "Square Reactive Flashers",
        roundCount: 10,
        timeLimit: "100 seconds",
        description: "Pushing standard velocity .22LR to its extreme subsonic limits. Flight times exceed 1.5 seconds per round.",
      },
    ],
    status: "SPOTS_FILLING",
    featured: true,
  },
  {
    id: "bristol-regional-qualifier",
    title: "East Tennessee Rimfire PRS Regional",
    subtitle: "Official Points Match for Mid-Atlantic & Southeast Precision Circuits",
    date: "November 14, 2026",
    time: "08:00 AM EST",
    location: "Bristol Mountain Complex, Range 2, Bristol, TN",
    locationDetails: "Hwy 421 Mountain Access, Bristol, TN",
    coordinates: {
      lat: 36.581,
      lng: -82.164,
    },
    tier: "REGIONAL_QUALIFIER",
    stages: 10,
    roundCount: 115,
    distanceRange: "40 – 310 Yards",
    maxCompetitors: 75,
    registeredCount: 42,
    entryFee: 110,
    prizePool: "$6,500 Prize Table",
    matchDirector: {
      name: "Caleb Sterling",
      callsign: "RO-CHIEF",
      email: "caleb@subsonicsociety.com",
      phone: "(423) 555-0144",
    },
    description:
      "A fast-paced regional qualifier featuring balanced barricades, tank traps, spool transitions, and positional rimfire challenges designed for regional rank points.",
    stageBriefs: [
      {
        stageNumber: 1,
        name: "Tank Trap Shuffle",
        distance: "95 yds",
        targetType: "Reactive Steel T-Post",
        roundCount: 10,
        timeLimit: "90 seconds",
        description: "Shoot 2 rounds each from 5 distinct pipe tips on the tank trap.",
      },
    ],
    status: "REGISTRATION_OPEN",
    featured: false,
  },
  {
    id: "subsonic-youth-academy",
    title: "Subsonic Society Precision Rimfire Clinic",
    subtitle: "Hands-on Masterclass: Wind Reading, Ballistic Solvers & Positional Stability",
    date: "December 5, 2026",
    time: "09:00 AM - 04:00 PM EST",
    location: "Subsonic Mountain Training Pavilion, Bristol, TN",
    locationDetails: "Clubhouse & Zero Bay, Bristol, TN",
    coordinates: {
      lat: 36.592,
      lng: -82.179,
    },
    tier: "CLINIC",
    stages: 5,
    roundCount: 150,
    distanceRange: "50 – 200 Yards",
    maxCompetitors: 30,
    registeredCount: 28,
    entryFee: 85,
    prizePool: "Certificates, Match Ammo & Subsonic Coins",
    matchDirector: {
      name: "Marcus Vance",
      callsign: "COACH-01",
      email: "academy@subsonicsociety.com",
      phone: "(423) 555-0122",
    },
    description:
      "Full day clinic taught by top PRS rimfire competitors. Learn DOPE card validation, cold bore zeroing, reading mountain mirage, and rapid target acquisition.",
    stageBriefs: [
      {
        stageNumber: 1,
        name: "Fundamentals of DOPE & Chronograph",
        distance: "50 yds & 100 yds",
        targetType: "Paper Grid & Chrono Screen",
        roundCount: 30,
        timeLimit: "Self-paced",
        description: "Truing muzzle velocity SD and BC validation through Kestrel 5700 solvers.",
      },
    ],
    status: "SPOTS_FILLING",
    featured: false,
  },
];

export const INITIAL_FACEBOOK_POSTS: FacebookPostItem[] = [
  {
    id: "fb-post-01",
    content:
      "⛰️ THE BRISTOL MOUNTAIN PRO IS COMING! Targets are going up on the ridge line in Bristol, TN. We have steel hung out to 465 yards with an average 18° drop angle into the mountain draw. Standard velocity .22LR ammo only. If you haven't chronographed your match batch yet, now is the time. Registration open on Subsonic Society!",
    publishedAt: "Yesterday at 4:15 PM",
    likesCount: 184,
    commentsCount: 39,
    sharesCount: 22,
    imageUrl: "/assets/subsonic-facebook-cover.jpg",
    externalUrl: "https://www.facebook.com/p/Subsonic-Society-61578052196057/",
    tags: ["#SubsonicSociety", "#BristolTN", "#PrecisionRimfire", "#22LR", "#PRSrimfire"],
  },
  {
    id: "fb-post-02",
    content:
      "🏆 Official 2026 Subsonic Society Challenge Coins have arrived from minting! Every competitor taking on the 18 stages at the Bristol Mountain Invitational will receive the official coin, with special gold-plated editions reserved for top podium finishers in Open, Production, and Senior divisions.",
    publishedAt: "3 days ago",
    likesCount: 312,
    commentsCount: 56,
    sharesCount: 41,
    imageUrl: "/assets/subsonic-coin.jpg",
    externalUrl: "https://www.facebook.com/p/Subsonic-Society-61578052196057/",
    tags: ["#SubsonicChallengeCoin", "#RimfireElite", "#PrecisionShooting", "#TennesseeRifle"],
  },
  {
    id: "fb-post-03",
    content:
      "🎯 Ballistics Spotlight: At 400+ yards, a 40gr subsonic .22LR round has over 1.4 seconds of flight time. Here's a look at the wind deflection chart through the Holston Mountain ridge cut. Watch for the mid-canyon updrafts at 220 yards that cause sudden vertical dispersals.",
    publishedAt: "5 days ago",
    likesCount: 147,
    commentsCount: 28,
    sharesCount: 19,
    imageUrl: "/assets/subsonic-facebook-cover.jpg",
    externalUrl: "https://www.facebook.com/p/Subsonic-Society-61578052196057/",
    tags: ["#RimfireBallistics", "#SubsonicData", "#KestrelDOPE", "#PrecisionShooting"],
  },
  {
    id: "fb-post-04",
    content:
      "🔥 Shoutout to our pro shooters dialling in their Vudoo V-22 and RimX chassis setups this weekend. High-magnification optics and smooth actions are dominating the leaderboards. What glass are you running in Bristol this fall?",
    publishedAt: "1 week ago",
    likesCount: 228,
    commentsCount: 64,
    sharesCount: 15,
    imageUrl: "/assets/subsonic-banner-wide.png",
    externalUrl: "https://www.facebook.com/p/Subsonic-Society-61578052196057/",
    tags: ["#RimfireRifles", "#RimX", "#VudooGunWorks", "#Optics", "#ChassisLife"],
  },
];

export const INITIAL_ATHLETES: AthleteProfile[] = [
  {
    id: "athlete-01",
    name: "Wyatt 'Ghost' Sterling",
    division: "Open Division Pro",
    ranking: "National Rank #4",
    homeRange: "Holston Range, Bristol, TN",
    rifleSetup: {
      action: "Vudoo V-22 3-Lug Rimfire",
      barrel: "Bartlein MTU 20\" Match 1:16 Twist",
      chassis: "MDT ACC Elite Carbon Titanium",
      optic: "Zero Compromise Optic ZC527 MPCT3X",
      ammo: "Lapua Center-X 40gr Subsonic",
    },
    quote: "In the Bristol mountains, the wind never blows the same way two seconds in a row. You have to trust your bubble level and read the grass on the draw.",
    imageUrl: "/assets/subsonic-logo-round.png",
    podiums: 14,
  },
  {
    id: "athlete-02",
    name: "Kendra 'Coldbore' Cross",
    division: "Open Rimfire Pro",
    ranking: "Southeast Regional Champion",
    homeRange: "Smoky Mountain Precision, TN",
    rifleSetup: {
      action: "Zermatt RimX Precision Action",
      barrel: "Proof Research Carbon 22\"",
      chassis: "Foundation Revelation Stock",
      optic: "Tangent Theta TT525P Gen 3XR",
      ammo: "SK Match Long Range 40gr",
    },
    quote: "Subsonic rimfire is pure shooting discipline. There is zero recoil to mask your flaws — every trigger squeeze and breath is on display.",
    imageUrl: "/assets/subsonic-logo-dark.png",
    podiums: 19,
  },
  {
    id: "athlete-03",
    name: "Eli 'Dialed' McAllister",
    division: "Production Division",
    ranking: "Appalachian Cup Winner",
    homeRange: "Tri-Cities Rimfire Club, Bristol, TN",
    rifleSetup: {
      action: "CZ 457 MTR Tuned",
      barrel: "Factory 20.5\" Match Chamber",
      chassis: "MDT XRS Hybrid Chassis",
      optic: "Vortex Razor HD Gen III 6-36x56",
      ammo: "ELEY Tenex 1058 fps Subsonic",
    },
    quote: "You don't need a $10,000 custom rig to win if you master stage timing and barricade stability.",
    imageUrl: "/assets/subsonic-coin.jpg",
    podiums: 8,
  },
];

export const INITIAL_CHAT_MESSAGES: ChatMessage[] = [
  {
    id: "msg-001",
    channelId: "bristol-pro-shootout",
    type: "MATCH_ALERT",
    author: {
      id: "user-md",
      name: "Garrett Vance",
      callsign: "DIRECTOR-01",
      role: "MATCH_DIRECTOR",
      badgeText: "MATCH DIRECTOR",
      division: "RANGE MASTER",
      rifleSetup: "Vudoo Official Chrono Spec",
    },
    content:
      "Welcome competitors to the 2026 Appalachian Mountain Rimfire Pro Invitational. Stage 1 through Stage 18 course of fire will be posted next week. Squad assignments go live Friday. Ensure your DOPE is true out to 465 yards!",
    timestamp: "10:14 AM",
    reactions: [
      { emoji: "🎯", count: 18, users: ["u1", "u2", "u3"] },
      { emoji: "🔥", count: 12, users: ["u4", "u5"] },
      { emoji: "⛰️", count: 9, users: ["u6"] },
    ],
    moderationStatus: "APPROVED",
    aiModerationReport: {
      toxicityScore: 0,
      threatScore: 0,
      policyScore: 0,
      sentiment: "POSITIVE",
      aiEngine: "Google Gemini 2.5 Flash",
    },
  },
  {
    id: "msg-002",
    channelId: "bristol-pro-shootout",
    type: "DOPE_DROP",
    author: {
      id: "user-wyatt",
      name: "Wyatt Sterling",
      callsign: "GHOST",
      role: "PRO_COMPETITOR",
      badgeText: "OPEN PRO",
      division: "Open Division Pro",
      rifleSetup: "Vudoo V-22 / Bartlein MTU 20\" / ZCO 527",
    },
    content:
      "Verified DOPE card for the 340-yard diamond plate on Stage 4. Lapua Center-X lot 32187 holding 1062 fps. Watch for the thermal lift off the lower draw.",
    dopeCard: {
      targetDistance: "340 YDS",
      targetDescription: "Stage 4 • Diamond KYL Rack",
      elevationMils: "8.4 MIL",
      windHoldMils: "L 0.6 MIL",
      windVelocity: "9 MPH @ 260° WNW",
      ammo: "Lapua Center-X 40gr (1,062 FPS)",
      densityAltitude: "+2,150 FT",
      notes: "Hold left-edge center. Downdraft causes 0.2 mil vertical drop if wind drops under 6 mph.",
    },
    timestamp: "10:45 AM",
    reactions: [
      { emoji: "🎯", count: 14, users: ["u1", "u7", "u9"] },
      { emoji: "👏", count: 8, users: ["u8"] },
      { emoji: "💡", count: 11, users: ["u2"] },
    ],
    moderationStatus: "APPROVED",
    aiModerationReport: {
      toxicityScore: 0,
      threatScore: 0,
      policyScore: 0,
      sentiment: "POSITIVE",
      aiEngine: "Google Gemini 2.5 Flash",
    },
  },
  {
    id: "msg-003",
    channelId: "ballistics-and-gear",
    type: "STANDARD",
    author: {
      id: "user-kendra",
      name: "Kendra Cross",
      callsign: "COLDBORE",
      role: "PRO_COMPETITOR",
      badgeText: "OPEN PRO",
      division: "Open Rimfire Pro",
      rifleSetup: "RimX / Proof Carbon 22\" / TT525P",
    },
    content:
      "For anyone asking about tuners on the RimX: The Harrell tuner clamped 1.5 inches back tightened our 100-yard group from 0.42 MOA to 0.28 MOA with SK Long Range. Worth every ounce of forward balance weight.",
    timestamp: "11:20 AM",
    reactions: [
      { emoji: "💡", count: 14, users: ["u1", "u2"] },
      { emoji: "🔥", count: 6, users: ["u3"] },
    ],
    moderationStatus: "APPROVED",
    aiModerationReport: {
      toxicityScore: 0,
      threatScore: 0,
      policyScore: 0,
      sentiment: "POSITIVE",
      aiEngine: "Google Gemini 2.5 Flash",
    },
  },
  {
    id: "msg-004",
    channelId: "general-society",
    type: "STANDARD",
    author: {
      id: "user-eli",
      name: "Eli McAllister",
      callsign: "DIALED",
      role: "MEMBER",
      badgeText: "PRODUCTION",
      division: "Production Division",
      rifleSetup: "CZ 457 MTR / Vortex Razor Gen III",
    },
    content:
      "Anyone travelling to Bristol from North Carolina wanting to share a cabin near South Holston Lake? Plenty of room for gear cases and loading benches.",
    timestamp: "12:05 PM",
    reactions: [{ emoji: "👍", count: 6, users: ["u3", "u4"] }],
    moderationStatus: "APPROVED",
    aiModerationReport: {
      toxicityScore: 2,
      threatScore: 0,
      policyScore: 0,
      sentiment: "POSITIVE",
      aiEngine: "Google Gemini 2.5 Flash",
    },
  },
  {
    id: "msg-005",
    channelId: "range-conditions-weather",
    type: "STANDARD",
    author: {
      id: "user-md",
      name: "Garrett Vance",
      callsign: "DIRECTOR-01",
      role: "MATCH_DIRECTOR",
      badgeText: "MATCH DIRECTOR",
      division: "RANGE MASTER",
      rifleSetup: "Kestrel 5700 Elite Link",
    },
    content:
      "Ridge weather update from Station 2 (Elevation 3,420 FT): Current winds 9 gusting 14 mph from 270° (WNW). Density altitude is sitting at +2,150 ft. Expect strong mirage on targets past 300 yards between 11:30 and 14:00.",
    timestamp: "12:30 PM",
    reactions: [
      { emoji: "⛰️", count: 15, users: ["u1", "u5"] },
      { emoji: "🎯", count: 9, users: ["u2"] },
    ],
    moderationStatus: "APPROVED",
    aiModerationReport: {
      toxicityScore: 0,
      threatScore: 0,
      policyScore: 0,
      sentiment: "POSITIVE",
      aiEngine: "Google Gemini 2.5 Flash",
    },
  },
  {
    id: "msg-006",
    channelId: "squad-briefings",
    type: "STANDARD",
    author: {
      id: "user-wyatt",
      name: "Wyatt Sterling",
      callsign: "GHOST",
      role: "PRO_COMPETITOR",
      badgeText: "SQUAD 3 LEAD",
      division: "Open Division Pro",
      rifleSetup: "Vudoo V-22 / Bartlein MTU 20\"",
    },
    content:
      "Squad 3 check-in: We start Stage 7 (The Tank Trap Barricade) at 08:30 Saturday. Bring extra chamber flags and 2 friction pads. Make sure your magazine extensions are clean.",
    timestamp: "1:15 PM",
    reactions: [
      { emoji: "👍", count: 7, users: ["u1", "u3"] },
      { emoji: "🎯", count: 4, users: ["u4"] },
    ],
    moderationStatus: "APPROVED",
    aiModerationReport: {
      toxicityScore: 0,
      threatScore: 0,
      policyScore: 0,
      sentiment: "POSITIVE",
      aiEngine: "Google Gemini 2.5 Flash",
    },
  },
  {
    id: "msg-007",
    channelId: "match-day-alerts",
    type: "MATCH_ALERT",
    author: {
      id: "user-md",
      name: "Garrett Vance",
      callsign: "DIRECTOR-01",
      role: "MATCH_DIRECTOR",
      badgeText: "MATCH DIRECTOR",
      division: "RANGE MASTER",
      rifleSetup: "Official Range Control",
    },
    content:
      "🚨 OFFICIAL NOTICE: Mandatory competitor safety briefing will commence at 07:15 AM sharp under Pavilion 1. Chronograph verification is open from 06:00 to 07:00 AM. Cold range rules in effect.",
    timestamp: "2:00 PM",
    reactions: [
      { emoji: "🎯", count: 24, users: ["u1", "u2", "u3", "u4", "u5"] },
      { emoji: "👏", count: 11, users: ["u6"] },
    ],
    moderationStatus: "APPROVED",
    aiModerationReport: {
      toxicityScore: 0,
      threatScore: 0,
      policyScore: 0,
      sentiment: "POSITIVE",
      aiEngine: "Google Gemini 2.5 Flash",
    },
  },
];
