import { MatchEvent, FacebookPostItem, AthleteProfile, ChatMessage } from "./types";

export const INITIAL_MATCHES: MatchEvent[] = [
  {
    id: "bristol-pro-invitational-2026",
    title: "Appalachian Mountain Rimfire Pro Invitational",
    subtitle: "The Premier Precision Rimfire Shootout in the Bristol TN High Country",
    date: "October 17-18, 2026",
    time: "07:00 AM EST Check-in",
    location: "Bristol Mountain Precision Facility, Bristol, TN",
    locationDetails: "Ridge Line Sector 4, Holston Mountain Valley, Bristol, TN 37620",
    coordinates: {
      lat: 36.5951,
      lng: -82.1887,
    },
    tier: "PRO_SERIES",
    stages: 18,
    roundCount: 220,
    distanceRange: "35 – 465 Yards",
    maxCompetitors: 120,
    registeredCount: 94,
    entryFee: 275,
    prizePool: "$28,500 Cash & Gear Table",
    matchDirector: {
      name: "Garrett 'Vapor' Vance",
      callsign: "MD-01",
      email: "director@subsonicsociety.com",
      phone: "(423) 555-0198",
    },
    description:
      "Perched high on the ridgeline overlooking the East Tennessee mountains, the Appalachian Mountain Pro Invitational tests competitors against drastic elevation changes, variable thermal mountain drafts, and steel targets stretched out to a staggering 465 yards. Pro shooters and top regional marksmen will battle across two grueling days for the coveted Subsonic Society Championship Cup and cash purse.",
    stageBriefs: [
      {
        stageNumber: 1,
        name: "Holston Gap High-Angle Sniper",
        distance: "185 yds – 340 yds",
        targetType: "66% IPSC & Diamond Steel",
        roundCount: 12,
        timeLimit: "90 seconds",
        description: "Engage targets from a steep 22-degree downhill natural boulder prop. Crosswind through the mountain notch requires aggressive wind holds.",
      },
      {
        stageNumber: 2,
        name: "The Bristol KYL Gauntlet",
        distance: "85 yds & 150 yds",
        targetType: "Know-Your-Limits 5-Paddles (2.0\" down to 0.25\")",
        roundCount: 10,
        timeLimit: "75 seconds",
        description: "Clean the near rack clean before moving to the 150-yard secondary rack. Any miss wipes all stage points earned so far.",
      },
      {
        stageNumber: 3,
        name: "Mountain Rooftop Positional",
        distance: "115 yds – 260 yds",
        targetType: "Round Gongs (4\" to 8\")",
        roundCount: 12,
        timeLimit: "90 seconds",
        description: "Fire two shots per target from three positions along a steep metal rooftop prop with slick footing.",
      },
      {
        stageNumber: 4,
        name: "Subsonic 400-Yard Terminal Glide",
        distance: "425 yds – 465 yds",
        targetType: "Square Reactive Flashers",
        roundCount: 10,
        timeLimit: "100 seconds",
        description: "Pushing standard velocity .22LR to its extreme subsonic limits. Flight times exceed 1.5 seconds per round.",
      },
    ],
    status: "SPOTS_FILLING",
    featured: true,
  },
  {
    id: "bristol-regional-qualifier",
    title: "East Tennessee Rimfire PRS Regional",
    subtitle: "Official Points Match for Mid-Atlantic & Southeast Precision Circuits",
    date: "November 14, 2026",
    time: "08:00 AM EST",
    location: "Bristol Mountain Complex, Range 2, Bristol, TN",
    locationDetails: "Hwy 421 Mountain Access, Bristol, TN",
    coordinates: {
      lat: 36.581,
      lng: -82.164,
    },
    tier: "REGIONAL_QUALIFIER",
    stages: 10,
    roundCount: 115,
    distanceRange: "40 – 310 Yards",
    maxCompetitors: 75,
    registeredCount: 42,
    entryFee: 110,
    prizePool: "$6,500 Prize Table",
    matchDirector: {
      name: "Caleb Sterling",
      callsign: "RO-CHIEF",
      email: "caleb@subsonicsociety.com",
      phone: "(423) 555-0144",
    },
    description:
      "A fast-paced regional qualifier featuring balanced barricades, tank traps, spool transitions, and positional rimfire challenges designed for regional rank points.",
    stageBriefs: [
      {
        stageNumber: 1,
        name: "Tank Trap Shuffle",
        distance: "95 yds",
        targetType: "Reactive Steel T-Post",
        roundCount: 10,
        timeLimit: "90 seconds",
        description: "Shoot 2 rounds each from 5 distinct pipe tips on the tank trap.",
      },
    ],
    status: "REGISTRATION_OPEN",
    featured: false,
  },
  {
    id: "subsonic-youth-academy",
    title: "Subsonic Society Precision Rimfire Clinic",
    subtitle: "Hands-on Masterclass: Wind Reading, Ballistic Solvers & Positional Stability",
    date: "December 5, 2026",
    time: "09:00 AM - 04:00 PM EST",
    location: "Subsonic Mountain Training Pavilion, Bristol, TN",
    locationDetails: "Clubhouse & Zero Bay, Bristol, TN",
    coordinates: {
      lat: 36.592,
      lng: -82.179,
    },
    tier: "CLINIC",
    stages: 5,
    roundCount: 150,
    distanceRange: "50 – 200 Yards",
    maxCompetitors: 30,
    registeredCount: 28,
    entryFee: 85,
    prizePool: "Certificates, Match Ammo & Sponsor Gear",
    matchDirector: {
      name: "Marcus Vance",
      callsign: "COACH-01",
      email: "academy@subsonicsociety.com",
      phone: "(423) 555-0122",
    },
    description:
      "Full day clinic taught by top PRS rimfire competitors. Learn DOPE card validation, cold bore zeroing, reading mountain mirage, and rapid target acquisition.",
    stageBriefs: [
      {
        stageNumber: 1,
        name: "Fundamentals of DOPE & Chronograph",
        distance: "50 yds & 100 yds",
        targetType: "Paper Grid & Chrono Screen",
        roundCount: 30,
        timeLimit: "Self-paced",
        description: "Truing muzzle velocity SD and BC validation through Kestrel 5700 solvers.",
      },
    ],
    status: "SPOTS_FILLING",
    featured: false,
  },
];

export const INITIAL_FACEBOOK_POSTS: FacebookPostItem[] = [
  {
    id: "fb-post-01",
    content:
      "⛰️ THE BRISTOL MOUNTAIN PRO IS COMING! Targets are going up on the ridge line in Bristol, TN. We have steel hung out to 465 yards with an average 18° drop angle into the mountain draw. Standard velocity .22LR ammo only. If you haven't chronographed your match batch yet, now is the time. Registration open on Subsonic Society!",
    publishedAt: "Yesterday at 4:15 PM",
    likesCount: 184,
    commentsCount: 39,
    sharesCount: 22,
    imageUrl: "/assets/subsonic-facebook-cover.jpg",
    externalUrl: "https://www.facebook.com/p/Subsonic-Society-61578052196057/",
    tags: ["#SubsonicSociety", "#BristolTN", "#PrecisionRimfire", "#22LR", "#PRSrimfire"],
  },
  {
    id: "fb-post-02",
    content:
      "🏆 Official 2026 Subsonic Society Invitational awards are finalized! Competitors taking on the 18 stages at The Hideout in Bristol, TN will battle for a guaranteed $7,500 cash purse presented by Modacam Custom Rifles across Open, Production, and Senior divisions.",
    publishedAt: "3 days ago",
    likesCount: 312,
    commentsCount: 56,
    sharesCount: 41,
    imageUrl: "/images/SS-RWB-LOGO.png",
    externalUrl: "https://www.facebook.com/p/Subsonic-Society-61578052196057/",
    tags: ["#SubsonicSociety", "#ModacamCustomRifles", "#PrecisionRimfire", "#CashPurse"],
  },
  {
    id: "fb-post-03",
    content:
      "🎯 Ballistics Spotlight: At 400+ yards, a 40gr subsonic .22LR round has over 1.4 seconds of flight time. Here's a look at the wind deflection chart through the Holston Mountain ridge cut. Watch for the mid-canyon updrafts at 220 yards that cause sudden vertical dispersals.",
    publishedAt: "5 days ago",
    likesCount: 147,
    commentsCount: 28,
    sharesCount: 19,
    imageUrl: "/assets/subsonic-facebook-cover.jpg",
    externalUrl: "https://www.facebook.com/p/Subsonic-Society-61578052196057/",
    tags: ["#RimfireBallistics", "#SubsonicData", "#KestrelDOPE", "#PrecisionShooting"],
  },
  {
    id: "fb-post-04",
    content:
      "🔥 Shoutout to our pro shooters dialling in their Vudoo V-22 and RimX chassis setups this weekend. High-magnification optics and smooth actions are dominating the leaderboards. What glass are you running in Bristol this fall?",
    publishedAt: "1 week ago",
    likesCount: 228,
    commentsCount: 64,
    sharesCount: 15,
    imageUrl: "/assets/subsonic-banner-wide.png",
    externalUrl: "https://www.facebook.com/p/Subsonic-Society-61578052196057/",
    tags: ["#RimfireRifles", "#RimX", "#VudooGunWorks", "#Optics", "#ChassisLife"],
  },
];

export const INITIAL_ATHLETES: AthleteProfile[] = [
  {
    id: "athlete-leipold",
    name: "Erich Leipold",
    division: "Open Rimfire Pro • Team USA",
    ranking: "Team USA 🇺🇸 • Rimfire Challenge World Champion",
    homeRange: "National Tour / Pennsylvania",
    rifleSetup: {
      action: "Zermatt RimX Precision Action",
      barrel: "Bartlein MTU Match Fluted 22\" (1:16 Twist)",
      chassis: "MasterPiece Arms (MPA) BA PMR Pro Chassis",
      optic: "Vortex Razor HD Gen III 6-36x56 EBR-7D",
      ammo: "Lapua Midas+ Hand-Sorted Lot",
    },
    quote: "Consistency isn't an accident. It's the byproduct of testing every variable, knowing your DOPE down to the tenth of a mil, and executing with absolute confidence.",
    imageUrl: "/assets/erich-leipold-poster.jpg",
    podiums: 61,
  },
  {
    id: "athlete-verran",
    name: "Ron Verran",
    division: "Open Rimfire Pro • Team USA",
    ranking: "2x PRS National Champion • Team USA 🇺🇸",
    homeRange: "Great Lakes Region / National Tour",
    rifleSetup: {
      action: "Zermatt RimX Precision Rimfire Action",
      barrel: "Bartlein MTU Match Fluted 22\" (1:16 Twist)",
      chassis: "MasterPiece Arms (MPA) Matrix Pro Competition Chassis",
      optic: "Vortex Razor HD Gen III 6-36x56 EBR-7D",
      ammo: "Lapua Center-X / Midas+ Hand-Sorted Lot",
    },
    quote: "It's not luck. It's a process.",
    imageUrl: "/assets/ron-verran-poster.jpg",
    podiums: 52,
  },
  {
    id: "athlete-hurley",
    name: "Allen Hurley",
    division: "Owner Admin / Executive",
    ranking: "Founder • Subsonic Society",
    homeRange: "The Hideout, Bristol, TN",
    rifleSetup: {
      action: "Modacam Custom Precision V-22 Rimfire",
      barrel: "22\" Custom Fluted Match Contour",
      chassis: "MDT ACC Elite Carbon Inlay Custom",
      optic: "Zero Compromise Optic ZC527",
      ammo: "Lapua Center-X Hand-Sorted",
    },
    quote: "We built The Hideout because rimfire precision deserves a home that doesn't cut corners. Two hundred and twenty acres of Tennessee ridgeline purpose-built for marksmen who take this game seriously. Said. Done.",
    imageUrl: "/images/SS-RWB-LOGO.png",
    podiums: 12,
  },
];

export const INITIAL_CHAT_MESSAGES: ChatMessage[] = [
  {
    id: "msg-ro-001",
    channelId: "invitational",
    type: "MATCH_ALERT",
    author: {
      id: "plink_ai_moderator",
      name: "RO BOT",
      callsign: "RO BOT",
      role: "OFFICIAL",
      badgeText: "AI Range Officer",
      division: "Autonomous AI Assistant • The Hideout",
      rifleSetup: "Autonomous AI Agent • Match Ops & Safety Telemetry",
    },
    content:
      "🤖 Welcome competitors to the 2026 Subsonic Society Invitational Money Match at The Hideout (Nov 13–15, 2026)! I am RO BOT, your 24/7 Autonomous AI Assistant and Range Officer. I have full operational intel on match schedules, the $2,500 cash side matches, the 220-acre facility, 12 Bristol hotel options, top dining spots (Blackbird Bakery is open 24h!), and local entertainment like South Holston River trophy trout fly fishing and the Hard Rock Casino.\n\n📖 Official Competitor Packet & Match Guide:\nhttps://subsonic-omega.vercel.app/competitor-packet\n\nSay 'hey ro' or ask '@ro help' anytime!",
    timestamp: "09:00 AM",
    reactions: [
      { emoji: "🎯", count: 32, users: ["u1", "u2", "u3", "u4", "u5"] },
      { emoji: "🏆", count: 21, users: ["u6", "u7", "u8"] },
      { emoji: "⛰️", count: 18, users: ["u9", "u10"] },
    ],
    moderationStatus: "APPROVED",
    aiModerationReport: {
      toxicityScore: 0,
      threatScore: 0,
      policyScore: 0,
      sentiment: "POSITIVE",
      aiEngine: "Autonomous AI Agent RO",
    },
  },
  {
    id: "msg-rob-001",
    channelId: "invitational",
    type: "STANDARD",
    author: {
      id: "usr_radar",
      name: "Rob Neilson",
      callsign: "RADAR",
      role: "MASTER_OWNER",
      badgeText: "MASTER ADMIN",
      division: "Master Admin",
      rifleSetup: "Systems & Infrastructure Architecture (Non-Shooter)",
    },
    content:
      "Telemetry relays and point-to-point direct comms are fully online across all 20 stages at The Hideout (3,420 FT). If any squad needs comms assistance or match network support during the weekend, ping me on direct line [RADAR].",
    timestamp: "09:45 AM",
    reactions: [
      { emoji: "👑", count: 31, users: ["u1", "u2", "u3", "u4", "u5"] },
      { emoji: "⚡", count: 24, users: ["u6", "u7", "u8"] },
      { emoji: "🎯", count: 19, users: ["u9", "u10"] },
    ],
    moderationStatus: "APPROVED",
    aiModerationReport: {
      toxicityScore: 0,
      threatScore: 0,
      policyScore: 0,
      sentiment: "POSITIVE",
      aiEngine: "Google Gemini 2.5 Flash",
    },
  },
  {
    id: "msg-leipold-001",
    channelId: "invitational",
    type: "STANDARD",
    author: {
      id: "usr_leipold",
      name: "Erich Leipold",
      callsign: "LEIPOLD",
      role: "PRO_COMPETITOR",
      badgeText: "TEAM USA 🇺🇸",
      division: "Open Rimfire Pro • Team USA",
      rifleSetup: "Zermatt RimX / Bartlein MTU 22\" / MPA BA PMR Pro",
    },
    content:
      "Rigs are tuned and looking forward to competing at The Hideout. The terrain out here in Bristol looks like it's going to make for a fantastic match. See everyone on the line.",
    timestamp: "10:15 AM",
    reactions: [
      { emoji: "🎯", count: 22, users: ["u1", "u2", "u3"] },
      { emoji: "🇺🇸", count: 18, users: ["u4", "u5"] },
    ],
    moderationStatus: "APPROVED",
    aiModerationReport: {
      toxicityScore: 0,
      threatScore: 0,
      policyScore: 0,
      sentiment: "POSITIVE",
      aiEngine: "Autonomous AI Agent RO",
    },
  },
  {
    id: "msg-verran-001",
    channelId: "invitational",
    type: "STANDARD",
    author: {
      id: "usr_verran",
      name: "Ron Verran",
      callsign: "VERRAN",
      role: "PRO_COMPETITOR",
      badgeText: "TEAM USA 🇺🇸",
      division: "Open Rimfire Pro • Team USA",
      rifleSetup: "Zermatt RimX / Bartlein MTU 22\" / MPA Matrix Pro",
    },
    content:
      "Excited to get out on the line with everyone. Bristol's high-angle terrain is going to test stage process and wind fundamentals. Remember: trust your process and stay calm on the barricades.",
    timestamp: "11:00 AM",
    reactions: [
      { emoji: "🏆", count: 25, users: ["u1", "u2", "u3"] },
      { emoji: "🎯", count: 19, users: ["u4", "u5"] },
    ],
    moderationStatus: "APPROVED",
    aiModerationReport: {
      toxicityScore: 0,
      threatScore: 0,
      policyScore: 0,
      sentiment: "POSITIVE",
      aiEngine: "Autonomous AI Agent RO",
    },
  },
  {
    id: "msg-007",
    channelId: "invitational",
    type: "MATCH_ALERT",
    author: {
      id: "user-allen",
      name: "Allen Hurley",
      callsign: "SAID DONE",
      role: "OWNER_ADMIN",
      badgeText: "FOUNDER",
      division: "Executive / Match Host",
      rifleSetup: "Modacam Custom Precision V-22 / ZCO 527",
    },
    content:
      "Welcome to The Hideout, marksmen. Two hundred and twenty acres of Tennessee ridgeline purpose-built for shooters who take precision rimfire seriously. Friday Welcome BBQ starts at 5:30 PM under the main pavilion. Take care of the property, shoot clean, and review the full weekend competitor guide at https://subsonic-omega.vercel.app/competitor-packet. Said. Done.",
    timestamp: "02:00 PM",
    reactions: [
      { emoji: "👑", count: 35, users: ["u1", "u2", "u3", "u4", "u5"] },
      { emoji: "🎯", count: 28, users: ["u6", "u7"] },
      { emoji: "👏", count: 22, users: ["u8"] },
    ],
    moderationStatus: "APPROVED",
    aiModerationReport: {
      toxicityScore: 0,
      threatScore: 0,
      policyScore: 0,
      sentiment: "POSITIVE",
      aiEngine: "Google Gemini 2.5 Flash",
    },
  },
  {
    id: "dm-allen-001",
    channelId: "dm_allen",
    type: "STANDARD",
    author: {
      id: "user-allen",
      name: "Allen Hurley",
      callsign: "SAID DONE",
      role: "OWNER_ADMIN",
      badgeText: "OWNER ADMIN",
      division: "Executive / Match Host",
      rifleSetup: "Modacam Custom Precision V-22 / ZCO 527",
    },
    content:
      "Welcome to private comms. All match staging and range operations at The Hideout (111 Hwy 44) are dialed in. Let me know if you need anything before check-in.",
    timestamp: "09:30 AM",
    reactions: [],
    moderationStatus: "APPROVED",
    aiModerationReport: {
      toxicityScore: 0,
      threatScore: 0,
      policyScore: 0,
      sentiment: "POSITIVE",
      aiEngine: "Google Gemini 2.5 Flash",
    },
  },
];
